return {
    schemas = {
        any = "valua.schemas.any",
        unknown = "valua.schemas.unknown",
        never = "valua.schemas.never",
        nil_ = "valua.schemas.nil_",
        ["nil"] = "valua.schemas.nil_",
        boolean = "valua.schemas.boolean",
        number = "valua.schemas.number",
        integer = "valua.schemas.integer",
        string = "valua.schemas.string",
        literal = "valua.schemas.literal",
        picklist = "valua.schemas.picklist",
        array = "valua.schemas.array",
        tuple = "valua.schemas.tuple",
        object = "valua.schemas.object",
        loose_object = "valua.schemas.loose_object",
        strict_object = "valua.schemas.strict_object",
        record = "valua.schemas.record",
        union = "valua.schemas.union",
        optional = "valua.schemas.optional",
        lazy = "valua.schemas.lazy",
        custom = "valua.schemas.custom",
    },
    actions = {
        check = "valua.actions.check",
        transform = "valua.actions.transform",
        non_empty = "valua.actions.non_empty",
        length = "valua.actions.length",
        min_length = "valua.actions.min_length",
        max_length = "valua.actions.max_length",
        min_value = "valua.actions.min_value",
        max_value = "valua.actions.max_value",
        multiple_of = "valua.actions.multiple_of",
        pattern = "valua.actions.pattern",
        starts_with = "valua.actions.starts_with",
        ends_with = "valua.actions.ends_with",
    },
    methods = {
        pipe = "valua.methods.pipe",
        parse = "valua.methods.parse",
        safe_parse = "valua.methods.safe_parse",
        is = "valua.methods.is",
    },
}
