local v = require("valua")

describe("Primitive Schemas", function()
    it("string schema", function()
        assert_true(v.is(v.string(), "hello"))
        assert_false(v.is(v.string(), 123))
        assert_false(v.is(v.string(), nil))
    end)

    it("number schema", function()
        assert_true(v.is(v.number(), 3.14))
        assert_true(v.is(v.number(), 42))
        assert_true(v.is(v.number(), math.huge))
        assert_false(v.is(v.number(), 0/0)) -- NaN rejected
        assert_false(v.is(v.number(), "42"))
    end)

    it("integer schema", function()
        assert_true(v.is(v.integer(), 42))
        assert_true(v.is(v.integer(), 0))
        assert_true(v.is(v.integer(), -100))
        assert_false(v.is(v.integer(), 3.14))
        assert_false(v.is(v.integer(), math.huge))
        assert_false(v.is(v.integer(), "42"))
    end)

    it("boolean schema", function()
        assert_true(v.is(v.boolean(), true))
        assert_true(v.is(v.boolean(), false))
        assert_false(v.is(v.boolean(), 1))
        assert_false(v.is(v.boolean(), nil))
    end)

    it("nil_ schema", function()
        assert_true(v.is(v.nil_(), nil))
        assert_false(v.is(v.nil_(), false))
        assert_false(v.is(v.nil_(), ""))
    end)

    it("any and unknown schemas", function()
        assert_true(v.is(v.any(), "str"))
        assert_true(v.is(v.any(), nil))
        assert_true(v.is(v.unknown(), 123))
    end)

    it("never schema", function()
        assert_false(v.is(v.never(), "anything"))
        assert_false(v.is(v.never(), nil))
    end)

    it("literal schema", function()
        local s = v.literal("admin")
        assert_true(v.is(s, "admin"))
        assert_false(v.is(s, "user"))
        assert_false(v.is(s, 123))
    end)

    it("picklist schema", function()
        local role = v.picklist({ "admin", "user", "guest" })
        assert_true(v.is(role, "admin"))
        assert_true(v.is(role, "guest"))
        assert_false(v.is(role, "superadmin"))
        assert_false(v.is(role, 123))
    end)
end)
