local v = require("valua")

describe("Validation & Transformation Actions", function()
    it("non_empty action", function()
        local s = v.pipe(v.string(), v.non_empty())
        assert_true(v.is(s, "hello"))
        assert_false(v.is(s, ""))
    end)

    it("min_length & max_length actions", function()
        local s = v.pipe(v.string(), v.min_length(3), v.max_length(5))
        assert_true(v.is(s, "abc"))
        assert_true(v.is(s, "abcde"))
        assert_false(v.is(s, "ab"))
        assert_false(v.is(s, "abcdef"))
    end)

    it("min_value & max_value actions", function()
        local n = v.pipe(v.number(), v.min_value(10), v.max_value(20))
        assert_true(v.is(n, 10))
        assert_true(v.is(n, 15))
        assert_true(v.is(n, 20))
        assert_false(v.is(n, 9))
        assert_false(v.is(n, 21))
    end)

    it("multiple_of action", function()
        local m = v.pipe(v.integer(), v.multiple_of(5))
        assert_true(v.is(m, 5))
        assert_true(v.is(m, 10))
        assert_false(v.is(m, 7))
    end)

    it("pattern action (Lua pattern)", function()
        local email = v.pipe(v.string(), v.pattern("^[^@]+@[^@]+$"))
        assert_true(v.is(email, "user@domain.com"))
        assert_false(v.is(email, "invalid-email"))
    end)

    it("starts_with & ends_with actions", function()
        local p = v.pipe(v.string(), v.starts_with("pre_"), v.ends_with("_post"))
        assert_true(v.is(p, "pre_data_post"))
        assert_false(v.is(p, "pre_data"))
        assert_false(v.is(p, "data_post"))
    end)

    it("transform action", function()
        local s = v.pipe(
            v.string(),
            v.transform(function(str) return string.upper(str) end)
        )
        local res = v.parse(s, "hello")
        assert_equal(res, "HELLO")
    end)
end)
