local parser = require("valua.tooling.luals.analyzer.parser")
local lexer = require("valua.tooling.luals.analyzer.lexer")

describe("Enhanced AST Parser Patterns", function()
    it("parses table calls without parentheses (v.object { ... })", function()
        local code = "local S = v.object { id = v.string() }"
        local toks = lexer.tokenize(code)
        local decls = parser.parse_tokens(toks)
        assert_equal(#decls, 1)
        assert_equal(decls[1].var_name, "S")
        assert_equal(decls[1].expr.type, "call")
        assert_equal(decls[1].expr.func, "object")
        assert_equal(decls[1].expr.namespace, "v")
        assert_true(decls[1].expr.args[1] ~= nil)
        assert_equal(decls[1].expr.args[1].type, "table")
    end)

    it("parses picklist with table literal without parentheses (v.picklist { ... })", function()
        local code = "local Status = v.picklist { 'active', 'inactive' }"
        local toks = lexer.tokenize(code)
        local decls = parser.parse_tokens(toks)
        assert_equal(#decls, 1)
        assert_equal(decls[1].var_name, "Status")
        assert_equal(decls[1].expr.type, "call")
        assert_equal(decls[1].expr.func, "picklist")
    end)

    it("parses string literal call without parentheses (v.literal 'admin')", function()
        local code = "local Role = v.literal 'admin'"
        local toks = lexer.tokenize(code)
        local decls = parser.parse_tokens(toks)
        assert_equal(#decls, 1)
        assert_equal(decls[1].var_name, "Role")
        assert_equal(decls[1].expr.type, "call")
        assert_equal(decls[1].expr.func, "literal")
        assert_equal(decls[1].expr.args[1].value, "admin")
    end)

    it("parses direct function calls from deep imports (object({ ... }))", function()
        local code = "local User = object({ name = string() })"
        local toks = lexer.tokenize(code)
        local decls = parser.parse_tokens(toks)
        assert_equal(#decls, 1)
        assert_equal(decls[1].var_name, "User")
        assert_equal(decls[1].expr.type, "call")
        assert_equal(decls[1].expr.func, "object")
        assert_equal(decls[1].expr.namespace, nil)
    end)

    it("handles incomplete pipeline gracefully while user is actively typing", function()
        local code = "local Name = v.pipe(v.string(), v.max_length(10), v.min_le"
        local toks = lexer.tokenize(code)
        local decls = parser.parse_tokens(toks)
        assert_equal(#decls, 1)
        assert_equal(decls[1].var_name, "Name")
        assert_equal(decls[1].expr.type, "call")
        assert_equal(decls[1].expr.func, "pipe")
    end)
end)
