local v = require("valua")

describe("Standard Schema v1 - Primitive Success", function()
    it("validates string success", function()
        local s = v.string()
        local res = s["~standard"].validate("hello")
        assert_equal(res.issues, nil)
        assert_equal(res.value, "hello")
    end)

    it("validates integer and number success", function()
        local int_s = v.integer()
        local res1 = int_s["~standard"].validate(42)
        assert_equal(res1.issues, nil)
        assert_equal(res1.value, 42)

        local num_s = v.number()
        local res2 = num_s["~standard"].validate(3.14159)
        assert_equal(res2.issues, nil)
        assert_equal(res2.value, 3.14159)
    end)

    it("validates boolean success", function()
        local s = v.boolean()
        local res = s["~standard"].validate(false)
        assert_equal(res.issues, nil)
        assert_equal(res.value, false)
    end)

    it("validates nil_ success with nil value and no issues (critical discriminator test)", function()
        local s = v.nil_()
        local res = s["~standard"].validate(nil)
        assert_equal(res.issues, nil, "Expected issues to be nil on successful nil_ schema")
        assert_equal(res.value, nil, "Expected value to be nil on nil_ schema")
    end)

    it("validates literal and picklist success", function()
        local lit = v.literal("active")
        local res1 = lit["~standard"].validate("active")
        assert_equal(res1.issues, nil)
        assert_equal(res1.value, "active")

        local pick = v.picklist({ "read", "write", "exec" })
        local res2 = pick["~standard"].validate("write")
        assert_equal(res2.issues, nil)
        assert_equal(res2.value, "write")
    end)
end)
