local v = require("valua")

describe("Standard Schema v1 - Primitive Failure", function()
    it("validates string failure without leaking value", function()
        local s = v.string()
        local res = s["~standard"].validate(123)
        assert_equal(res.value, nil)
        assert_true(type(res.issues) == "table")
        assert_true(#res.issues >= 1)
        assert_true(type(res.issues[1].message) == "string")
    end)

    it("validates integer failure on floats and strings", function()
        local s = v.integer()
        local res = s["~standard"].validate(3.14)
        assert_equal(res.value, nil)
        assert_true(type(res.issues) == "table")
        assert_true(#res.issues >= 1)
    end)

    it("validates never failure on all inputs", function()
        local s = v.never()
        local res = s["~standard"].validate("anything")
        assert_equal(res.value, nil)
        assert_true(type(res.issues) == "table")
        assert_true(#res.issues >= 1)
    end)
end)
